name: Android CI

on:
  push:
    tags:
      - 'v*' # 当你推送以 v 开头的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'build-tools;34.0.0' # Example: Install version 34.0.0 explicitly

      # 自动上传到 Release 页面
#      - name: Upload APK
#        uses: softprops/action-gh-release@v1
#        with:
#          files: app/build/outputs/apk/release/*.apk
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK with Tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/BaptizingLight-${TAG_NAME}.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: BaptizingLight-${{ github.ref_name }}
          path: app/build/outputs/apk/release/BaptizingLight-${{ github.ref_name }}.apk
